### PR TITLE
Add command to convert rules from fritzmg/contao-short-urls

### PR DESCRIPTION
**Pull request by rabauss**
Besides the command I also added a new field `comment` to mark the converted rules - it's just for internal use.

This branch relies on xliff files from https://github.com/terminal42/contao-url-rewrite/pull/20 - but I would rebase that, if the PR is accepted. Unfortunately, the Cs fix also makes it a bit confusing  ;-)

### CODE REVIEW

**Comment by Toflar** [comment]
Hmm...not sure if we want this in this bundle. It's just another burden to maintain.
On the other hand, I understand that you would want to centralize this somewhere and not make yet another bundle nobody will ever discover.

To me this is a very general use case. After all, we're talking migrating from extension A to extension B. I wonder if we shouldn't work on some general solution for all extension developers?
We now have `contao:migrate` as a general migration framework for all extensions. Wouldn't it be great to have a "standardized" way to migrate from extension A to extension B?
Like `contao-migrate-extension <recipe>`. So everybody could contribute their recipes and we could  have a `fritzmg/contao-short-urls-to-terminal42/contao-url-rewrite` or `woocommerce-to-isotope` migration or whatever?

I just think there would be a higher chance of users actually discovering such migrations and it would also be easier for developers if we had a framework because the foundation is already there.

**Comment by rabauss** [comment]
Yes, we needed this command for a customer because we even implemented an Excel import there for URL rewrites.
But since I also wanted to make the command available to the community, I was just thinking about packing it into an extra extension that no one would find. I am fully with you that a general solution would be the nicer one!

While implementing this command I was even thinking about using the contao migrations - but can I define them as optional?

**Comment by Toflar** [comment]
Afaik there's no such thing currently. But I'd be intrested in @ausi's opinion on that.

**Comment by ausi** [comment]
The migrations framework in Contao is meant to be executable without user interaction so I don’t think optional migrations are a good fit into this system.

But could’t the migration itself check if it needs to be executed? I think if the new extension (e.g. `terminal42/contao-url-rewrite`) is installed and the old one (e.g. `fritzmg/contao-short-urls`) isn’t anymore but data from the old extension is still present the migration can assume that the data needs to be migrated.

**Comment by rabauss** [comment]
I simulated this scenario with my method `canConvert` - analogous to `shouldRun` of `AbstractMigration`.
But I wasn't sure if everyone really wanted to convert all "legacy" short urls with both extensions installed.
Therefore I decided to implement a command instead of a migration - to start the conversion manually!

**Comment by Toflar** [comment]
Acutally, I didn't plan to incorporate it into `contao:migrate`. That's a different use case because they need to be able to run at all times. This here is a one-off process that needs to be triggered manually and very likely the migration recipes would also want to ask questions during that process. Not sure this would be something for core anyway. At least not until the process has proven to be a good one.

I don't want this piece of code in this bundle because 
a) I don't want to maintain it
b) it makes no sense that developers come up with their own solutions and commands in various extensions

**Comment by rabauss** [comment]
Okay, for now my solution would be that we could release that tiny command as own small extension with dependencies on both extension - although we do not want to maintain that either :-D But since short urls are abandoned there should be no changes coming up from that direction.

Nevertheless, I think the solution of a new extension migration handling would be a nice feature of contao core - maybe as mentioned: `contao:migrate:extension`?

**Comment by Toflar** [comment]
> Okay, for now my solution would be that we could release that tiny command as own small extension with dependencies on both extension - although we do not want to maintain that either :-D

I'd suggest you start with a general purpose extension. Not one that is specifically designed for this migration only. Maybe it gains some traction in the community. Then we can iron out design issues and eventually check if we want something like this in the core?

**Comment by richardhj** [comment]
Closing : )

**Pull request closed without merging**
