### PR TITLE
Make name optional

### PR DESCRIPTION
**Pull request by dmolineus**
This PR allows to leave the name blank. If the name is blank it's copied from the request path.

### CODE REVIEW

**Comment by Toflar** [comment]
Fine for me, wdyt @qzminski ?

**Comment by dmolineus** [comment]
I improved it a bit. I added missing unit tests and try to get the `requestPath` from the current request as the `activeRecord` might be not updated with the current value.

**Comment by Toflar** [comment]
Thank you @dmolineus! I want to release 1.3.0 asap because of the cache bugfix. Would be great if you could review and test the `develop` branch on your projects 👍

**Comment by dmolineus** [comment]
> Thank you @dmolineus! I want to release 1.3.0 asap because of the cache bugfix. Would be great if you could review and test the develop branch on your projects +1

Great news. I work on the project tomorrow so I'll be able to test it really soon. Another issue I stumbled upon: In Contao 4.7 the routes defined by this extension are listed before the routes provided by Contao. Would be nice if the Contao routes would come first. Gonna check it as well if your changes have affects to the behaviour.

**Comment by Toflar** [comment]
That's fine imho. A redirect rule should have higher priority than a page. That's correct.

**Comment by dmolineus** [comment]
> That's fine imho. A redirect rule should have higher priority than a page. That's correct.

In the current use case some urls have changed from `category-item.html` to `category/item.html`. There is a fallback rewrite rule which autodetect the rules. However, there are still other pages which follows the  `category-item.html` schema and shouldn't be rewritten. Decrasing priority for such rules would solve the problem so that an editor could manage the page structure without thinking about the rewrite rules. 

At least it would be helpful to have an option for this behaviour.

**Comment by Toflar** [comment]
That's clearly not a use case for this bundle.

**Comment by dmolineus** [comment]
> That's clearly not a use case for this bundle.

Okay. Sad, but I undertand that you don't wanna expand the scope of the extension too far. Gonna have to build a custom solution for such requirements from my project.

**Comment by Toflar** [comment]
I mean, it's not even possible for Contao 4.4. With the CMF router we could have two routers, one before the Contao Router (the regular Symfony router, like it is now) and one after the Contao Router. But that won't happen until 4.9 is released and we can drop support for 4.4.

**Pull request merged**
