### PR TITLE
Fix dependencies for symfony 5

### PR DESCRIPTION
**Pull request by rabauss**
This PR solves #23 and depends on #25! Finally, I added all symfony requirements from the code.

But I wanted to discuss separately whether `symfony/expression-language` is really necessary as a requirement because it's not used in the code like @m-vo said!

What do you think?

### CODE REVIEW

**Comment by richardhj** [comment]
Thank you. This is correct. Maybe `expression-language` was considered but never implemented.

**Comment by fritzmg** [comment]
This extension does support expression language for the advanced configuration of redirect conditions.

**Comment by richardhj** [comment]
Nah, then I'd better add it back.

**Comment by richardhj** [comment]
@fritzmg It looks like the feature was removed. Can you confirm? Or show the usage in the code?

**Comment by richardhj** [comment]
From the docs (https://symfony.com/doc/current/routing.html#matching-expressions), it shouldn't be necessary to add the expression language as dependency. 
From the composer.json, it is required to add the dependency. So Fritz is correct.

**Comment by fritzmg** [comment]
Yes, it is not used by the extension directly - but the extension supports the expression language in `terminal42_url_rewrite.entries.request.condition`/`tl_url_rewrite.requestCondition` which is used for the `condition` of a route.

**Pull request merged**
